# Site settings
title: "Venkata Subba Reddy | Growth Product Leader"
email: "subbar77@gmail.com"
description: >-
  Growth Product Manager with 6+ years of experience in architecting 
  automated conversion engines and scalable MarTech ecosystems.
  BITS Pilani & ESADE Alumnus.

# Professional Identity
url: "https://subbar-77.github.io" 
baseurl: "" 

# Social Integration
linkedin_username: "Venkata Subba Reddy Kachireddy" # Update with your exact LinkedIn handle
github_username:  "subbar-77"

# Theme Customization (Minima 3.0)
theme: minima
minima:
  skin: dark # Gives your portfolio a modern, technical aesthetic
  social_links:
    - { platform: github, user_url: "https://github.com/subbar-77" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/venkatasubbareddykachireddy/" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag
